// src/lib/schemas/production.js
export const SCHEMA_64 = [
  { key: "sel", label: "Sel.", type: "checkbox", width: 60 },
  { key: "detail", label: "Détail", type: "button", width: 100 },
  { key: "zone", label: "Zone", type: "text", width: 120 },
  { key: "piece", label: "Pièce", type: "text", width: 120 },
  { key: "produit", label: "Produit", type: "select", options: ["Rideau", "Voilage", "Store Bateau", "Store Enrouleur", "Store Vénitien", "Cache Sommier", "Coussin", "Décor de lit", "Autres"], width: 140 },
  { key: "type_confection", label: "Type de confection", type: "select", options: ["Wave 80", "Wave 60", "Couteau", "Flamand", "Triplis", "Creux", "Taylor", "Tuyaux d'orgue", "Plat", "A plat"], width: 160 },
  { key: "pair_un", label: "Paire / Un seul pan", type: "select", options: ["Paire", "Un seul pan"], width: 150 },
  { key: "ampleur", label: "Ampleur", type: "number", precision: 2, width: 90 },
  { key: "l_mecanisme", label: "Largeur mécanisme", type: "number", width: 150 },
  { key: "largeur", label: "Largeur", type: "number", width: 110 },
  { key: "hauteur", label: "Hauteur", type: "number", width: 110 },
  { key: "statut_cotes", label: "Statut Cotes", type: "select", options: ["Pas prises", "Côtes sur plans", "Côtes approximatives", "Côtes définitives"], width: 180 },
  { key: "f_bas", label: "Finition bas", type: "number", width: 120 },
  { key: "croisement", label: "Croisement", type: "number", width: 120 },
  { key: "retour_g", label: "Retour Gauche", type: "number", width: 130 },
  { key: "retour_d", label: "Retour Droit", type: "number", width: 120 },
  { key: "envers_visible", label: "Envers visible", type: "select", options: ["Oui", "Non"], width: 120 },
  { key: "double", label: "Doublé", type: "select", options: ["Oui", "Non"], width: 100 },
  { key: "h_tete", label: "Hauteur de tête", type: "number", width: 130 },
  { key: "type_rail", label: "Type de rail", type: "select", options: ["Kontrak", "Projekt", "Tekno", "Mini", "Separa 20mm", "Separa 28mm", "Tringle 40mm", "Tringle 31mm", "Free"], width: 160 },
  { key: "couleur_rail", label: "Couleur rail", type: "text", width: 140 },
  { key: "nom_tringle", label: "Nom Tringle", type: "text", width: 160 },
  { key: "diametre_tringle", label: "Diamètre Tringle", type: "select", options: ["2,5", "2,8", "3,1", "3,3", "3,5", "4", "5"], width: 150 },
  { key: "couv_mecanisme", label: "Couverture mécanisme", type: "select", options: ["Couvert", "MiCouvert", "Découvert"], width: 170 },
  { key: "supp_mecanisme", label: "Support mécanisme", type: "text", width: 180 },
  { key: "nb_glisseurs", label: "Nombre de glisseur/anneaux", type: "formula", formula: "ROUND({l_mecanisme}/10 + 2, 0)", width: 200, readOnly: true },
  { key: "type_pose", label: "Type de pose", type: "text", width: 140 },
  { key: "statut_preparation", label: "Statut Préparation", type: "select", options: ["No go", "Go", "Commencé", "Terminé"], width: 180 },
  { key: "statut_pose", label: "Statut Pose", type: "select", options: ["No go", "Go", "Commencé", "A parfaire", "Terminé", "Reprise"], width: 160 },
  { key: "val_ded_rail", label: "Valeur déduction rail", type: "number", width: 170 },
  { key: "h_finie", label: "Hauteur finie", type: "formula", formula: "{hauteur} - {val_ded_rail} + {f_bas}", width: 140, readOnly: true },
  { key: "l_finie", label: "Largeur finie", type: "formula", formula: "IF({pair_un}=='Paire', {largeur}/2 + 10 + {retour_g}+{retour_d}+{croisement}, {largeur} + 10 + {retour_g}+{retour_d}+{croisement})", width: 150, readOnly: true },
  { key: "a_plat", label: "A plat", type: "formula", formula: "({l_finie}*{ampleur})+({val_ourlet_cote}*4)", width: 140, readOnly: true },
  { key: "val_ourlet_cote", label: "Valeur ourlet de côté", type: "number", width: 160 },
  { key: "val_ourlet_haut", label: "Valeur ourlet haut", type: "number", width: 160 },
  { key: "piquage_bas", label: "Piquage ourlet du bas", type: "text", width: 160 },
  { key: "f_bas_type", label: "Finition ourlet du bas", type: "text", width: 160 },
  { key: "poids", label: "Poids", type: "number", width: 120 },
  { key: "onglet", label: "Onglet", type: "select", options: ["oui", "non"], width: 100 },
  { key: "commentaire_confection", label: "Commentaire confection", type: "text", width: 220 },
  { key: "tissu_deco1", label: "Tissu Déco 1", type: "text", width: 160 },
  { key: "laize_tissu_deco1", label: "Laize Tissu Déco 1", type: "number", width: 160 },
  { key: "motif_deco1", label: "Motif Déco 1", type: "select", options: ["oui", "non"], width: 120 },
  { key: "raccord_v1", label: "Raccord Vertical 1", type: "number", width: 150 },
  { key: "raccord_h1", label: "Raccord Horizontal 1", type: "number", width: 150 },
  { key: "tissu_deco2", label: "Tissu Déco 2", type: "text", width: 160 },
  { key: "laize_tissu_deco2", label: "Laize Tissu Déco 2", type: "number", width: 160 },
  { key: "motif_deco2", label: "Motif Déco 2", type: "select", options: ["oui", "non"], width: 120 },
  { key: "raccord_v2", label: "Raccord Vertical 2", type: "number", width: 150 },
  { key: "raccord_h2", label: "Raccord Horizontal 2", type: "number", width: 150 },
  { key: "passementerie1", label: "Passementerie 1", type: "text", width: 150 },
  { key: "app_passementerie1", label: "Application Passementerie 1", type: "text", width: 200 },
  { key: "passementerie2", label: "Passementerie 2", type: "text", width: 150 },
  { key: "app_passementerie2", label: "Application Passementerie 2", type: "text", width: 200 },
  { key: "doublure", label: "Doublure", type: "text", width: 120 },
  { key: "laize_doublure", label: "Laize Doublure", type: "number", width: 140 },
  { key: "inter_doublure", label: "Interdoublure", type: "text", width: 140 },
  { key: "laize_inter", label: "Laize Interdoublure", type: "number", width: 160 },
  { key: "h_coupe_tissu", label: "Hauteur de coupe tissu", type: "formula", formula: "{h_finie} + ({val_ourlet_cote}*2) + ({h_tete}*2) + 10", width: 200, readOnly: true },
  { key: "h_coupe_tissu_motif", label: "Hauteur de coupe tissu motif", type: "formula", formula: "ROUND({h_coupe_tissu}/{raccord_v1},0)*{raccord_v1}", width: 240, readOnly: true },
  { key: "h_coupe_doublure", label: "Hauteur de coupe Doublure", type: "formula", formula: "IF({h_coupe_tissu}<280, {a_plat}, {h_coupe_tissu})", width: 220, readOnly: true },
  { key: "nb_les", label: "A plat / Laize tissu déco 1 (nb lés)", type: "formula", formula: "MAX(1,ROUNDUP({a_plat}/{laize_tissu_deco1},0))", width: 260, readOnly: true },
  { key: "statut_confection", label: "Statut Confection", type: "select", options: ["No go", "Go", "Coupé", "Terminé", "Reprise"], width: 180 },
  { key: "heures_confection", label: "Heures confection", type: "number", width: 150 },
  { key: "heures_pose", label: "Heures pose", type: "number", width: 130 },
  { key: "photo", label: "Photo prise sur site", type: "photo", width: 200 },
  { key: "croquis", label: "Croquis", type: "croquis", width: 200 },
];